---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  # Disabled for the moment, due to Code Climate bug.
  rubocop:
    enabled: false
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
